[package]
id = xmlutils

[id]
version = 1.2.3
name = xmlutils

[install]
is_configured = false
state = enabled
build = 123

[ui]
is_visible = false
is_manageable = false
label = xmlutils

[launcher]
author = vbumgarner
description = XML utilities
version = 1.2.3
